AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.coniungo.app::aws-java-lambda

Parameters:
  DBHost:
    Type: String
    Description: RDS Hostname
  DBPort:
    Type: String
    Default: "5432"
    Description: RDS Port
  DBName:
    Type: String
    Description: Database name
  DBUser:
    Type: String
    Description: Database username
  DBPassword:
    Type: String
    Description: Database password
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for Lambda functions
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet IDs for Lambda functions
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Security Group IDs for Lambda functions

Globals:
  Api:
    EndpointConfiguration: REGIONAL
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java21
    Architectures:
      - x86_64
    Environment:
      Variables:
        DB_HOST: !Ref DBHost
        DB_PORT: !Ref DBPort
        DB_NAME: !Ref DBName
        DB_USER: !Ref DBUser
        DB_PASSWORD: !Ref DBPassword
    VpcConfig:
      SubnetIds: !Ref SubnetIds
      SecurityGroupIds: !Ref SecurityGroupIds

Resources:
  ConiungoUserServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      TracingEnabled: true

  GetAllUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: com.coniungo.app.handlers.GetAllUsersHandler::handleRequest
      Events:
        GetAllUsersApi:
          Type: Api
          Properties:
            Path: /api/v1/users
            Method: get
            RestApiId: !Ref ConiungoUserServiceApi

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: com.coniungo.app.handlers.GetUserHandler::handleRequest
      Events:
        GetUserApi:
          Type: Api
          Properties:
            Path: /api/v1/user
            Method: get
            RestApiId: !Ref ConiungoUserServiceApi

Outputs:
  AwsJavaLambdaApi:
    Description: "Base URL for the API"
    Value: !Sub "https://${ConiungoUserServiceApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"


  GetAllUsersFunctionArn:
    Description: "ARN for GetAllUsers Lambda"
    Value: !GetAtt GetAllUsersFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-GetAllUsersArn"

  GetUserFunctionArn:
    Description: "ARN for GetUser Lambda"
    Value: !GetAtt GetUserFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-GetUserArn"
